### ISSUE TITLE
Android No such file or directory

### ISSUE THREAD

**Issue by sawaca96** [AppsFlyerSDK/appsflyer-capacitor-plugin#103]
# Report

## Plugin Version

```
"appsflyer-capacitor-plugin": "~6.12.1",
"@capacitor/android": "^5.0.0",
```

## On what Platform are you having the issue?

android

## What did you do?

```
npx cap open android

npx cap sync android

Sync project with gradle files (android studio ->  file)
```

## What did you expect to happen?

no error raised

## What happened instead?

below error raised

```
A problem occurred evaluating project ':appsflyer-capacitor-plugin'.
> packages/mobile/android/../node_modules/appsflyer-capacitor-plugin/package.json (No such file or directory)
```

## Please provide any other relevant information.

When I was using version`~6.9.2`, I had no problem, but when I modified the version to `~6.12.1` while doing capacitor5 migrate, I got this error.

**Comment by sawaca96** [comment]
I think it's because of the monorepo.


https://github.com/AppsFlyerSDK/appsflyer-capacitor-plugin/blob/d70c1b717c5d4edd2a64a010c9b218c5419ab2b9/android/build.gradle#L4C5-L4C19

If you look at the function in the link above

function is looking for package.json in `../node_modules`, but it's actually a monorepo, so I think it should be in `../../../node_modules`.

**Comment by sawaca96** [comment]
I make PR 

https://github.com/AppsFlyerSDK/appsflyer-capacitor-plugin/pull/104

check this please 🙏

**Comment by paulisch** [comment]
In case you are using `nx` you can work your way around that using `"nohoist"` inside of the `"workspaces"` declaration in your `packages.json`. There you can put the path to your app which moves the `node_modules` for this one from the global level to the workspace-level.

**Comment by sawaca96** [comment]
O-ha....! 

@paulisch Thanks🙏 I will try

**Comment by pazlavi** [comment]
Hey @sawaca96 
Can you please try this alpha version and let us know if it solves the issue for you? 
```bash
npm install appsflyer-capacitor-plugin@6.12.1-alpha-monorepo
```

**Comment by kpturner** [comment]
I have the exact same problem so I will try version 6.12.1-alpha-monorepo

**Comment by kpturner** [comment]
That version worked fine thankyou

**Comment by sawaca96** [comment]
I works me too thanks! 😄
