### ISSUE TITLE
[FEATURE]: Add required `Privacy Manifest` file for iOS

### ISSUE THREAD

**Issue by edshkliaruk** [AppsFlyerSDK/appsflyer-capacitor-plugin#109]
**Description**

Starting with Spring 2024 Apple requires third-party SDKs to add a Privacy Manifest file (similar to the privacy nutrition labels in the store). Apple specifically lists Capacitor as one of the SDKs that must include this manifest otherwise any App that includes it is not allowed to release an update (or new app) to the store.

https://developer.apple.com/support/third-party-SDK-requirements/

**Platform(s)**

iOS

**Additional Context**
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests
https://developer.apple.com/videos/play/wwdc2023/10060/

**Comment by pazlavi** [comment]
Hi @edshkliaruk. 
The document you shared refers to the Capacitor framework, not the AppsFlyer Plugin. 
For more information about AppsFlyer and Privacy Manifest, please visit [this article](https://support.appsflyer.com/hc/en-us/articles/21677433322641-Privacy-Manifest).

For additional help, please open a support ticket at support@appsflyer.com.

**Comment by edshkliaruk** [comment]
@pazlavi Hello, thank you for answering, as I understood AppsFlyer SDK should add Privacy Manifest file?

**Comment by pazlavi** [comment]
As mentioned [here](https://support.appsflyer.com/hc/en-us/articles/21677433322641-Privacy-Manifest#do-i-have-to-update-my-appsflyer-sdk), down the road, our SDK will include a Privacy Manifest.
