### ISSUE TITLE
Add support for Capacitor v6

### ISSUE THREAD

**Issue by woutersteven** [AppsFlyerSDK/appsflyer-capacitor-plugin#119]
Capacitor 6 has been released last week. It would be great if AppsFlyer can add support for it.

- Release: https://ionic.io/blog/announcing-capacitor-6-0
- Changelog: https://github.com/ionic-team/capacitor/blob/main/CHANGELOG.md

**Comment by pazlavi** [comment]
Hi @woutersteven, 
It's currently in our backlog bug, and I don't have any ETA to share yet.

**Comment by CalumMurray** [comment]
Hi @pazlavi, is there any update on an ETA here, please? It's currently the only plugin we have that's blocking our Capacitor upgrade.

**Comment by bboldi** [comment]
> Hi @pazlavi, is there any update on an ETA here, please? It's currently the only plugin we have that's blocking our Capacitor upgrade.

Second :point_up: this ... This is the only plugin that holds us back from upgrading to capacitor 6 ... an ETA would be appreciated. Thanks!

**Comment by bboldi** [comment]
Hi! Any ETA on this? Thanks!

**Comment by gzeus0911** [comment]
Any update?

**Comment by benmarsh** [comment]
Just wanted to add another request for this please - it's the last SDK on our list that doesn't have v6 support yet. Would be great to get it added in and be able to ship our updated app with Capacitor 6. Thanks!

**Comment by benmarsh** [comment]
Just adding this for info, I emailed support for any additional updates and had the following response - pretty much the same as above;

> Hi Ben,
> The estimated release timeline to upgrade our Capacitor v6 is currently being discussed with the Product and R&D teams.
> We do not have any clarity about when this will be available as the team seeks to start researching it soon.
> Please follow the GitHub page for updates: https://github.com/AppsFlyerSDK/appsflyer-capacitor-plugin
> Thanks!

If the AppsFlyer team are able to share any further details on this as it progresses that would be great.

**Comment by danziv** [comment]
Same here.
Would greatly appreciate a quick solution or some clarity on the expected timeframe.

**Comment by trinitiwowka** [comment]
The same 
<img width="701" alt="image" src="https://github.com/AppsFlyerSDK/appsflyer-capacitor-plugin/assets/8225740/7a8480a1-def0-4ede-ba45-bfc3bc8c0164">

**Comment by RobAndrsn** [comment]
This is a bit concerning, unless I'm missing something. I was informed by capacitor team that "If you're not using Cap 6 by August 31 then the Play Store may not offer the app on Android 14+ devices." 

This plugin is blocking our team from upgrade to capacitor 6

**Comment by benmarsh** [comment]
@RobAndrsn agreed it is concerning, and also a little disappointing. We chose AppsFlyer as an MMP as they had a specific Capacitor integration vs other competitors. We are in the same position where this is blocking our upgrade path also.

Assuming the bundled native AppsFlyer SDKs remains the same then the PR submitted recently by @taretmch should be enough to offer initial support for Capacitor 6...?

**Comment by HaasStefan** [comment]
Any updates? We would like to integrate AppsFlyer into our Capacitor 6 application. @pazlavi

**Comment by dnlrbz** [comment]
> Hi @woutersteven, It's currently in our backlog bug, and I don't have any ETA to share yet.

@pazlavi @Dani-Koza-AF Hi, can you please update the plugin to capacitor 6? This blocks us from using it. There is already a PR for it https://github.com/AppsFlyerSDK/appsflyer-capacitor-plugin/pull/130

**Comment by Matt-Winfield-Derivco** [comment]
Is there anything blocking #130 from being merged? Or any updates? This is preventing us from upgrading to Cap 6, which is important to get done ASAP as we need to target version 34 by August 31st, which requires Capacitor v6.

**Comment by bboldi** [comment]
Can I bump this? Anyone has anything on this? Android deadline is getting closer, so we'll HAVE to upgrade to Capacitor 6 asap, need time for testing as well...

**Comment by Dani-Koza-AF** [comment]
Capacitor v6 upgrade is in progress and will be published in the beginning of next week. (11th Aug)

**Comment by MaxCode2023** [comment]
> Обновление Capacitor v6 находится в процессе разработки и будет опубликовано в начале следующей недели. (11 августа)

Please tell me when to expect an update?

**Comment by bboldi** [comment]
It's out finally https://github.com/AppsFlyerSDK/appsflyer-capacitor-plugin/releases/tag/6.15.0

**Comment by taretmch** [comment]
Thanks!
I've closed this pull request #130.
