### ISSUE TITLE
iOS `setResolveDeepLinkURLs()` broken

### ISSUE THREAD

**Issue by katie-propel** [AppsFlyerSDK/appsflyer-capacitor-plugin#143]
# Report

## Plugin Version

6.15.1 (and older)

## On what Platform are you having the issue?

iOS

## What did you do?

Deeplinks opened from emails will not resolve correctly.

## What did you expect to happen?

Deeplinks will take you to the destination specified in the Onelink template configuration.

## What happened instead?

Emails only open the app without deeplink redirects.

## Please provide any other relevant information.

I found the problem. It looks like a copy-paste error. Please review this PR: https://github.com/AppsFlyerSDK/appsflyer-capacitor-plugin/pull/131

**Comment by Dani-Koza-AF** [comment]
Thanks for the catch, will be fixed in the next release.

**Comment by Dani-Koza-AF** [comment]
Fixed on v6.15.2 (will be released tomorrow).
