### ISSUE TITLE
No variants found for ':appsflyer-capacitor-plugin'. Check build files to ensure at least one variant exists. 

### ISSUE THREAD

**Issue by fujahgabriel** [AppsFlyerSDK/appsflyer-capacitor-plugin#19]
<img width="1335" alt="Screenshot 2022-03-31 at 14 44 08" src="https://user-images.githubusercontent.com/15958955/161069900-a60b21b2-d157-4463-96c3-0c084278c56a.png">

**Comment by pazlavi** [comment]
👋 Hi @fujahgabriel  and Thank you for reaching out to us.
            In order for us to provide optimal support, please submit a ticket to our support team at support@appsflyer.com.
            When submitting the ticket, please specify:
            - ✅ your AppsFlyer sign-up (account) email
            - ✅ app ID
            - ✅ steps for reproduce
            - ✅ logs
            - ✅ code snippets
            - ✅ and any additional relevant information.

**Comment by pazlavi** [comment]
👋 Hi @fujahgabriel  and Thank you for reaching out to us.
In order for us to provide optimal support, please submit a ticket to our support team at support@appsflyer.com.
When submitting the ticket, please specify:
- ✅ your AppsFlyer sign-up (account) email
- ✅ app ID
- ✅ steps for reproduce
- ✅ logs
- ✅ code snippets
- ✅ and any additional relevant information.
