### ISSUE TITLE
Unable to open ATT prompt screen

### ISSUE THREAD

**Issue by smrgrg** [AppsFlyerSDK/appsflyer-capacitor-plugin#21]
Hi, I'm currently using appsflyer-capacitor-plugin:6.4.4 in an ionic angular app, but unable to open the ATT prompt. 

I've implemented in this fashion as mentioned [in the docs here.](https://github.com/AppsFlyerSDK/appsflyer-capacitor-plugin/blob/main/docs/BasicIntegration.md)

Then, also added NSUserTrackingUsageDescription as mentioned [here](https://developer.apple.com/documentation/apptrackingtransparency). I was unable to carry steps 2 and 3 because it's related to native code change, which is probably handled by the sdk.

However, I've tried many times but could not open the ATT prompt.

**Comment by pazlavi** [comment]
Hi @smrgrg, 
Thank you for reaching out to us.

Did you follow [this](https://github.com/AppsFlyerSDK/appsflyer-capacitor-plugin/blob/main/docs/AdvancedAPI.md#-collect-idfa-with-attrackingmanager) guide? 
Showing the ATT prompt is not part of AppsFlyer SDK.
If any further assistance is required here, we would kindly ask you to submit a support ticket to support@appsflyer.com.
When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.

**Comment by smrgrg** [comment]
Thanks @pazlavi After I installed the third party plugin as mentioned in the [doc](https://github.com/AppsFlyerSDK/appsflyer-capacitor-plugin/blob/main/docs/AdvancedAPI.md#-collect-idfa-with-attrackingmanager), I was able to open the ATT prompt.
