### ISSUE TITLE
Is this plugin compatible with Capacitor v2 ?

### ISSUE THREAD

**Issue by sneko** [AppsFlyerSDK/appsflyer-capacitor-plugin#22]
Hi,

I'm trying to build the iOS version of this plugin but I face multiple issues like:
```
Type 'Notification.Name' (aka 'NSNotification.Name') has no member 'capacitorOpenURL'
```

I compared v2.5 and v3.0 of Capacitor:
* https://github.com/ionic-team/capacitor/blob/2.5.0/ios/Capacitor/Capacitor/CAPNotifications.swift#L14-L19
* https://github.com/ionic-team/capacitor/blob/3.0.0/ios/Capacitor/Capacitor/CAPNotifications.swift#L22-L28

and it seems the change means your plugin is only for Capacitor v3. Can you confirm?

Thank you,

cc @pazlavi

**Comment by pazlavi** [comment]
Hi @sneko,
Thank you for reaching out to us.
Yes, our plugin is built for Capacitor 3 and above.

**Comment by sneko** [comment]
I took a few hours to upgrade everything to Capacitor v3.... and I'm now able to install your plugin :)

But:
- Unfortunately I'm not able to test the SDK from your dashboard, just opened a ticket with the support (in case you can have a look) (I disabled Firebase Dynamic Links to test)
- Have another technical question, will open a new issue
