### ISSUE TITLE
Capacitor v4 support

### ISSUE THREAD

**Issue by MateiNenciu** [AppsFlyerSDK/appsflyer-capacitor-plugin#29]
Is there any work in progress to support Capacitor v4? Currently our app cannot use this plugin anymore because we upgraded to v4. 
I can submit a PR if needed to help with migration. Thanks

**Comment by pazlavi** [comment]
Hi @MateiNenciu 
Thank you for reaching out to us.

Please see #27 , and #28.

**Comment by MateiNenciu** [comment]
I saw those but I swill do not agree with this. You shouldn't "punish" users that want to upgrade and keep up with the flow. You are basically forcing us to find other behind the scenes ways to upgrade (and maintain those ways which include more complexity). 

In my opinion you should release a 7.0.0 version with support for capacitor v4 and new deployment targets.

**Comment by MateiNenciu** [comment]
I've made a PR for those who wants to both use this plugin and capacitor v4: https://github.com/AppsFlyerSDK/appsflyer-capacitor-plugin/pull/30

**Comment by EKashpersky** [comment]
Also needed 👀

**Comment by bboldi** [comment]
Almost all of the other capacitor plugins v4 (14 of them in my app) only Appsflyer did not ... we can use 'hacks' to make it work I assume, but wouldn't it be time to update it? Or if it's crucial to "not punish users who don't want to update", maybe to offer both versions?

**Comment by Benjadahl** [comment]
We need this as well - any updates?

**Comment by pazlavi** [comment]
We are running a QA cycle for a new version supporting Capacitor 4. We expect to release this version by the end of the next week. 
MR: #33

**Comment by Benjadahl** [comment]
Thanks a lot for prioritising this!

**Comment by CalumMurray** [comment]
Our team would love to have this supported. Any updates on estimated time of support please?

**Comment by Hambat** [comment]
Any news?

**Comment by pazlavi** [comment]
We just released v6.9.2, which supports Capacitor v4. 
If you still wish to use Capacitor v3, please check [this page ](https://github.com/AppsFlyerSDK/appsflyer-capacitor-plugin/blob/main/docs/Installation.md#-capacitor-3---latest-version).
