### ISSUE TITLE
Incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.

### ISSUE THREAD

**Issue by iOlivier** [AppsFlyerSDK/appsflyer-capacitor-plugin#31]
When adding the capacitor plugin to our project, the build fails for Android (while iOS works as expected).

Below the error it throws in the Android Studio build output:
`/Users/olivier/.gradle/caches/transforms-2/files-2.1/08eae3c9229602786c5328e473ff0a3f/jetified-core-ktx-1.6.0-api.jar!/META-INF/core-ktx_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.`

Any idea what this is about?

Below a list of the capacitor stuff we use:
```
    "@capacitor-community/fcm": "^2.0.2",
    "@capacitor-community/firebase-analytics": "^1.0.0",
    "@capacitor/android": "3.3.3",
    "@capacitor/app": "^1.0.6",
    "@capacitor/camera": "^1.2.0",
    "@capacitor/core": "^3.3.0",
    "@capacitor/device": "^1.0.6",
    "@capacitor/haptics": "^1.1.3",
    "@capacitor/ios": "^3.3.0",
    "@capacitor/keyboard": "^1.1.3",
    "@capacitor/network": "1.0.7",
    "@capacitor/push-notifications": "^1.0.7",
    "@capacitor/status-bar": "1.0.8",
    "@hoi/components-ui": "0.0.15",
    "@ionic-native/badge": "^5.28.0",
    "@ionic-native/barcode-scanner": "^5.28.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/deeplinks": "^5.28.0",
    "@ionic-native/device": "^5.36.0",
    "@ionic-native/keyboard": "^5.28.0",
    "@ionic-native/open-native-settings": "^5.36.0",
    "@ionic-native/social-sharing": "^5.28.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "appsflyer-capacitor-plugin": "6.8.0",
    "capacitor-ios-autofill-save-password": "^1.1.2",
 ```

**Comment by pazlavi** [comment]
Hi @iOlivier,
Thank you for reaching out to us.
You need to increase your `kotlin_version` to at least `1.5.1`.
You can see more info [here](https://stackoverflow.com/a/67816693)

**Comment by iOlivier** [comment]
Hi @pazlavi,
Updating it to `1.5.10` made the error go away.
Thanks
