### ISSUE TITLE
Cannot install Plugin on iOS - Pod Error

### ISSUE THREAD

**Issue by mariusbolik** [AppsFlyerSDK/appsflyer-capacitor-plugin#5]
I get the following error running `npx cap sync ios`:

<img width="1046" alt="Bildschirmfoto 2021-09-13 um 10 51 55" src="https://user-images.githubusercontent.com/39862171/133054087-3062801b-820a-49f7-8e1a-799ccbee0a1b.png">

The App is not designed for Kids. What do I have to do to get the plugin installed?

**Comment by pazlavi** [comment]
Hi @mariusbolik  ,
Thank you for reaching out to us.

Please try to add  `s.static_framework = true` to the `AppsflyerCapacitorPlugin.podspec `file.

**Comment by mariusbolik** [comment]
Thank you for the prompt response. This file is in the `node_modules` folder. The file will be overwritten when updating the plugin. Also all my team members have to adjust the file because the `node_modules` folder isn't in git. There must be a better solution.

**Comment by pazlavi** [comment]
@mariusbolik 
I'm sorry for the inconvenience, but I'm not familiar with another solution. A new version will be released during the upcoming days with the fix.

**Comment by pazlavi** [comment]
@mariusbolik Please update to V6.4.0.

**Comment by mariusbolik** [comment]
V6.4.0 fixes the problem. Thank you 🙏

**Comment by paulohps-lyncas** [comment]
hello, I'm using version 6.5.2 and I get the same error, is there any solution?

**Comment by piyushnh** [comment]
Hello, I'm using version 6.8.0, still facing the same issue. Could you help with it please?

**Comment by pazlavi** [comment]
@piyushnh 
To provide optimal support, we would kindly ask you to submit a support ticket to support@appsflyer.com.

When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.
