### ISSUE TITLE
Getting error while trying to compile ios app for iPhone SE2 iOS 14 but not for emulator

### ISSUE THREAD

**Issue by bboldi** [AppsFlyerSDK/appsflyer-capacitor-plugin#8]
When I try to run complied ionic application on my iPhone SE2 i get this error

`ld: in /Users/user/Library/Developer/Xcode/DerivedData/App-eismujpzjeytykgfdircgvnuefmj/Build/Products/Debug-iphoneos/AppsFlyerLib.framework/AppsFlyerLib(AFSDKDevice.o), building for iOS, but linking in object file (/Users/user/Library/Developer/Xcode/DerivedData/App-eismujpzjeytykgfdircgvnuefmj/Build/Products/Debug-iphoneos/AppsFlyerLib.framework/AppsFlyerLib(AFSDKDevice.o)) built for Mac Catalyst, file '/Users/user/Library/Developer/Xcode/DerivedData/App-eismujpzjeytykgfdircgvnuefmj/Build/Products/Debug-iphoneos/AppsFlyerLib.framework/AppsFlyerLib' for architecture arm64`

Version 13.0 (13A233)
iPhone SE 2
IOS 14.8

plugin appsflyer-capacitor-plugin@6.4.0

I trid to update cocoapods to latest, xcode to latest, plugin to latest, and different solution, like changing the `ONLY_ACTIVE_ARCH = YES` and `NO` then adding `EXCLUDED_ARCHS arm64` , and so on, but nothing helps ... nothing seems to be helping ...

interestingly, if I select an emulator, it compiles and runs fine

also if i use the command

`npx cap run ios`

it compiles and runs on the physical device fine ... I spent 2 days already trying to fix this, really frustrating ... please help.

**Comment by pazlavi** [comment]
Hi @bboldi ,
Thank you for reaching out to us.

To provide optimal support, we would kindly ask you to submit a support ticket to support@appsflyer.com.

When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.

**Comment by bboldi** [comment]
This helped ( got answer from AppsFlyer support )

```
XCode has a "DerivedData" folder where it stores some of the intermediate data it uses during the build process. By default it's located in ~/Library/Developer/Xcode/DerivedData. Cleaning this folder by deleting it can resolve some build issues.
```

Thanks!
