### ISSUE TITLE
Upgrade to Capacitor 5?

### ISSUE THREAD

**Issue by dev-blinov** [AppsFlyerSDK/appsflyer-capacitor-plugin#95]
Is there an update planned to support Capacitor 5?

**Comment by jskrepnek** [comment]
@pazlavi Are there any active plans at the moment to do this work?

**Comment by gelinger777** [comment]
+1

**Comment by jefflnorton** [comment]
+1

**Comment by f1ght4fun** [comment]
When is this going to happen !? Almost everyone moved and upgraded their plugins to support Cap 5.

Please advise!

**Comment by bboldi** [comment]
+1

**Comment by MateiNenciu** [comment]
https://github.com/AppsFlyerSDK/appsflyer-capacitor-plugin/pull/96 use this PR till an update is available

**Comment by KevinToala** [comment]
+1
